// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/hmly.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHouseholdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHouseholdRequest) Reset() {
	*x = CreateHouseholdRequest{}
	mi := &file_proto_hmly_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHouseholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHouseholdRequest) ProtoMessage() {}

func (x *CreateHouseholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hmly_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHouseholdRequest.ProtoReflect.Descriptor instead.
func (*CreateHouseholdRequest) Descriptor() ([]byte, []int) {
	return file_proto_hmly_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHouseholdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetHouseholdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseholdId   string                 `protobuf:"bytes,1,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHouseholdRequest) Reset() {
	*x = GetHouseholdRequest{}
	mi := &file_proto_hmly_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHouseholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHouseholdRequest) ProtoMessage() {}

func (x *GetHouseholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hmly_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHouseholdRequest.ProtoReflect.Descriptor instead.
func (*GetHouseholdRequest) Descriptor() ([]byte, []int) {
	return file_proto_hmly_proto_rawDescGZIP(), []int{1}
}

func (x *GetHouseholdRequest) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

type GetHouseHoldsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHouseHoldsRequest) Reset() {
	*x = GetHouseHoldsRequest{}
	mi := &file_proto_hmly_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHouseHoldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHouseHoldsRequest) ProtoMessage() {}

func (x *GetHouseHoldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hmly_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHouseHoldsRequest.ProtoReflect.Descriptor instead.
func (*GetHouseHoldsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hmly_proto_rawDescGZIP(), []int{2}
}

func (x *GetHouseHoldsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetHouseHoldsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UpdateHouseholdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseholdId   string                 `protobuf:"bytes,1,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHouseholdRequest) Reset() {
	*x = UpdateHouseholdRequest{}
	mi := &file_proto_hmly_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHouseholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHouseholdRequest) ProtoMessage() {}

func (x *UpdateHouseholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hmly_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHouseholdRequest.ProtoReflect.Descriptor instead.
func (*UpdateHouseholdRequest) Descriptor() ([]byte, []int) {
	return file_proto_hmly_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateHouseholdRequest) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

func (x *UpdateHouseholdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateHouseholdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseholdId   string                 `protobuf:"bytes,1,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ErrorMessage  *Error                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHouseholdResponse) Reset() {
	*x = CreateHouseholdResponse{}
	mi := &file_proto_hmly_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHouseholdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHouseholdResponse) ProtoMessage() {}

func (x *CreateHouseholdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hmly_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHouseholdResponse.ProtoReflect.Descriptor instead.
func (*CreateHouseholdResponse) Descriptor() ([]byte, []int) {
	return file_proto_hmly_proto_rawDescGZIP(), []int{4}
}

func (x *CreateHouseholdResponse) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

func (x *CreateHouseholdResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHouseholdResponse) GetErrorMessage() *Error {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

type HouseholdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ErrorMessage  *Error                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseholdResponse) Reset() {
	*x = HouseholdResponse{}
	mi := &file_proto_hmly_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseholdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseholdResponse) ProtoMessage() {}

func (x *HouseholdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hmly_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseholdResponse.ProtoReflect.Descriptor instead.
func (*HouseholdResponse) Descriptor() ([]byte, []int) {
	return file_proto_hmly_proto_rawDescGZIP(), []int{5}
}

func (x *HouseholdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HouseholdResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HouseholdResponse) GetErrorMessage() *Error {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_hmly_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hmly_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_hmly_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HouseholdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Households    []*HouseholdResponse   `protobuf:"bytes,1,rep,name=households,proto3" json:"households,omitempty"`
	ErrorMessage  *Error                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseholdsResponse) Reset() {
	*x = HouseholdsResponse{}
	mi := &file_proto_hmly_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseholdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseholdsResponse) ProtoMessage() {}

func (x *HouseholdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hmly_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseholdsResponse.ProtoReflect.Descriptor instead.
func (*HouseholdsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hmly_proto_rawDescGZIP(), []int{7}
}

func (x *HouseholdsResponse) GetHouseholds() []*HouseholdResponse {
	if x != nil {
		return x.Households
	}
	return nil
}

func (x *HouseholdsResponse) GetErrorMessage() *Error {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

var File_proto_hmly_proto protoreflect.FileDescriptor

const file_proto_hmly_proto_rawDesc = "" +
	"\n" +
	"\x10proto/hmly.proto\x12\x03api\",\n" +
	"\x16CreateHouseholdRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"8\n" +
	"\x13GetHouseholdRequest\x12!\n" +
	"\fhousehold_id\x18\x01 \x01(\tR\vhouseholdId\"D\n" +
	"\x14GetHouseHoldsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"O\n" +
	"\x16UpdateHouseholdRequest\x12!\n" +
	"\fhousehold_id\x18\x01 \x01(\tR\vhouseholdId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x98\x01\n" +
	"\x17CreateHouseholdResponse\x12!\n" +
	"\fhousehold_id\x18\x01 \x01(\tR\vhouseholdId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x124\n" +
	"\rerror_message\x18\x03 \x01(\v2\n" +
	".api.ErrorH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\"\x7f\n" +
	"\x11HouseholdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x124\n" +
	"\rerror_message\x18\x03 \x01(\v2\n" +
	".api.ErrorH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x94\x01\n" +
	"\x12HouseholdsResponse\x126\n" +
	"\n" +
	"households\x18\x01 \x03(\v2\x16.api.HouseholdResponseR\n" +
	"households\x124\n" +
	"\rerror_message\x18\x02 \x01(\v2\n" +
	".api.ErrorH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message2\xee\x02\n" +
	"\x10HouseholdService\x12F\n" +
	"\x0fCreateHousehold\x12\x1b.api.CreateHouseholdRequest\x1a\x16.api.HouseholdResponse\x12@\n" +
	"\fGetHousehold\x12\x18.api.GetHouseholdRequest\x1a\x16.api.HouseholdResponse\x12C\n" +
	"\rGetHouseholds\x12\x19.api.GetHouseHoldsRequest\x1a\x17.api.HouseholdsResponse\x12F\n" +
	"\x0fUpdateHousehold\x12\x1b.api.UpdateHouseholdRequest\x1a\x16.api.HouseholdResponse\x12C\n" +
	"\x0fDeleteHousehold\x12\x18.api.GetHouseholdRequest\x1a\x16.api.HouseholdResponseB&Z$github.com/hmlylab/hmly/common/protob\x06proto3"

var (
	file_proto_hmly_proto_rawDescOnce sync.Once
	file_proto_hmly_proto_rawDescData []byte
)

func file_proto_hmly_proto_rawDescGZIP() []byte {
	file_proto_hmly_proto_rawDescOnce.Do(func() {
		file_proto_hmly_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hmly_proto_rawDesc), len(file_proto_hmly_proto_rawDesc)))
	})
	return file_proto_hmly_proto_rawDescData
}

var file_proto_hmly_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_hmly_proto_goTypes = []any{
	(*CreateHouseholdRequest)(nil),  // 0: api.CreateHouseholdRequest
	(*GetHouseholdRequest)(nil),     // 1: api.GetHouseholdRequest
	(*GetHouseHoldsRequest)(nil),    // 2: api.GetHouseHoldsRequest
	(*UpdateHouseholdRequest)(nil),  // 3: api.UpdateHouseholdRequest
	(*CreateHouseholdResponse)(nil), // 4: api.CreateHouseholdResponse
	(*HouseholdResponse)(nil),       // 5: api.HouseholdResponse
	(*Error)(nil),                   // 6: api.Error
	(*HouseholdsResponse)(nil),      // 7: api.HouseholdsResponse
}
var file_proto_hmly_proto_depIdxs = []int32{
	6, // 0: api.CreateHouseholdResponse.error_message:type_name -> api.Error
	6, // 1: api.HouseholdResponse.error_message:type_name -> api.Error
	5, // 2: api.HouseholdsResponse.households:type_name -> api.HouseholdResponse
	6, // 3: api.HouseholdsResponse.error_message:type_name -> api.Error
	0, // 4: api.HouseholdService.CreateHousehold:input_type -> api.CreateHouseholdRequest
	1, // 5: api.HouseholdService.GetHousehold:input_type -> api.GetHouseholdRequest
	2, // 6: api.HouseholdService.GetHouseholds:input_type -> api.GetHouseHoldsRequest
	3, // 7: api.HouseholdService.UpdateHousehold:input_type -> api.UpdateHouseholdRequest
	1, // 8: api.HouseholdService.DeleteHousehold:input_type -> api.GetHouseholdRequest
	5, // 9: api.HouseholdService.CreateHousehold:output_type -> api.HouseholdResponse
	5, // 10: api.HouseholdService.GetHousehold:output_type -> api.HouseholdResponse
	7, // 11: api.HouseholdService.GetHouseholds:output_type -> api.HouseholdsResponse
	5, // 12: api.HouseholdService.UpdateHousehold:output_type -> api.HouseholdResponse
	5, // 13: api.HouseholdService.DeleteHousehold:output_type -> api.HouseholdResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_hmly_proto_init() }
func file_proto_hmly_proto_init() {
	if File_proto_hmly_proto != nil {
		return
	}
	file_proto_hmly_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_hmly_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_hmly_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hmly_proto_rawDesc), len(file_proto_hmly_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hmly_proto_goTypes,
		DependencyIndexes: file_proto_hmly_proto_depIdxs,
		MessageInfos:      file_proto_hmly_proto_msgTypes,
	}.Build()
	File_proto_hmly_proto = out.File
	file_proto_hmly_proto_goTypes = nil
	file_proto_hmly_proto_depIdxs = nil
}
