// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: hmly.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHouseholdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHouseholdRequest) Reset() {
	*x = CreateHouseholdRequest{}
	mi := &file_hmly_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHouseholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHouseholdRequest) ProtoMessage() {}

func (x *CreateHouseholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHouseholdRequest.ProtoReflect.Descriptor instead.
func (*CreateHouseholdRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHouseholdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetHouseholdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHouseholdRequest) Reset() {
	*x = GetHouseholdRequest{}
	mi := &file_hmly_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHouseholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHouseholdRequest) ProtoMessage() {}

func (x *GetHouseholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHouseholdRequest.ProtoReflect.Descriptor instead.
func (*GetHouseholdRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{1}
}

func (x *GetHouseholdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetHouseHoldsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHouseHoldsRequest) Reset() {
	*x = GetHouseHoldsRequest{}
	mi := &file_hmly_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHouseHoldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHouseHoldsRequest) ProtoMessage() {}

func (x *GetHouseHoldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHouseHoldsRequest.ProtoReflect.Descriptor instead.
func (*GetHouseHoldsRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{2}
}

func (x *GetHouseHoldsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetHouseHoldsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UpdateHouseholdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHouseholdRequest) Reset() {
	*x = UpdateHouseholdRequest{}
	mi := &file_hmly_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHouseholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHouseholdRequest) ProtoMessage() {}

func (x *UpdateHouseholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHouseholdRequest.ProtoReflect.Descriptor instead.
func (*UpdateHouseholdRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateHouseholdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateHouseholdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateHouseholdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ErrorMessage  *Error                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHouseholdResponse) Reset() {
	*x = CreateHouseholdResponse{}
	mi := &file_hmly_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHouseholdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHouseholdResponse) ProtoMessage() {}

func (x *CreateHouseholdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHouseholdResponse.ProtoReflect.Descriptor instead.
func (*CreateHouseholdResponse) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{4}
}

func (x *CreateHouseholdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateHouseholdResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHouseholdResponse) GetErrorMessage() *Error {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

type HouseholdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ErrorMessage  *Error                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseholdResponse) Reset() {
	*x = HouseholdResponse{}
	mi := &file_hmly_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseholdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseholdResponse) ProtoMessage() {}

func (x *HouseholdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseholdResponse.ProtoReflect.Descriptor instead.
func (*HouseholdResponse) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{5}
}

func (x *HouseholdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HouseholdResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HouseholdResponse) GetErrorMessage() *Error {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

func (x *HouseholdResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *HouseholdResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_hmly_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HouseholdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Households    []*HouseholdResponse   `protobuf:"bytes,1,rep,name=households,proto3" json:"households,omitempty"`
	ErrorMessage  *Error                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseholdsResponse) Reset() {
	*x = HouseholdsResponse{}
	mi := &file_hmly_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseholdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseholdsResponse) ProtoMessage() {}

func (x *HouseholdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseholdsResponse.ProtoReflect.Descriptor instead.
func (*HouseholdsResponse) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{7}
}

func (x *HouseholdsResponse) GetHouseholds() []*HouseholdResponse {
	if x != nil {
		return x.Households
	}
	return nil
}

func (x *HouseholdsResponse) GetErrorMessage() *Error {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

type CreateMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseholdId   string                 `protobuf:"bytes,1,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemberRequest) Reset() {
	*x = CreateMemberRequest{}
	mi := &file_hmly_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberRequest) ProtoMessage() {}

func (x *CreateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberRequest.ProtoReflect.Descriptor instead.
func (*CreateMemberRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{8}
}

func (x *CreateMemberRequest) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

func (x *CreateMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRequest) Reset() {
	*x = GetMemberRequest{}
	mi := &file_hmly_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRequest) ProtoMessage() {}

func (x *GetMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRequest.ProtoReflect.Descriptor instead.
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{9}
}

func (x *GetMemberRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseholdId   string                 `protobuf:"bytes,1,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersRequest) Reset() {
	*x = GetMembersRequest{}
	mi := &file_hmly_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersRequest) ProtoMessage() {}

func (x *GetMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersRequest.ProtoReflect.Descriptor instead.
func (*GetMembersRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{10}
}

func (x *GetMembersRequest) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

type UpdateMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HouseholdId   string                 `protobuf:"bytes,2,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRequest) Reset() {
	*x = UpdateMemberRequest{}
	mi := &file_hmly_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRequest) ProtoMessage() {}

func (x *UpdateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateMemberRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMemberRequest) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

func (x *UpdateMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HouseholdId   string                 `protobuf:"bytes,2,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ErrorMessage  *Error                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberResponse) Reset() {
	*x = MemberResponse{}
	mi := &file_hmly_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberResponse) ProtoMessage() {}

func (x *MemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberResponse.ProtoReflect.Descriptor instead.
func (*MemberResponse) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{12}
}

func (x *MemberResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemberResponse) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

func (x *MemberResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MemberResponse) GetErrorMessage() *Error {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

func (x *MemberResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MemberResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*MemberResponse      `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	ErrorMessage  *Error                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembersResponse) Reset() {
	*x = MembersResponse{}
	mi := &file_hmly_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersResponse) ProtoMessage() {}

func (x *MembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersResponse.ProtoReflect.Descriptor instead.
func (*MembersResponse) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{13}
}

func (x *MembersResponse) GetMembers() []*MemberResponse {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *MembersResponse) GetErrorMessage() *Error {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

type CreateMealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HouseholdId   string                 `protobuf:"bytes,2,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMealRequest) Reset() {
	*x = CreateMealRequest{}
	mi := &file_hmly_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMealRequest) ProtoMessage() {}

func (x *CreateMealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMealRequest.ProtoReflect.Descriptor instead.
func (*CreateMealRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{14}
}

func (x *CreateMealRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMealRequest) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

type GetMealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMealRequest) Reset() {
	*x = GetMealRequest{}
	mi := &file_hmly_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMealRequest) ProtoMessage() {}

func (x *GetMealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMealRequest.ProtoReflect.Descriptor instead.
func (*GetMealRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{15}
}

func (x *GetMealRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMealsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseholdId   string                 `protobuf:"bytes,1,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMealsRequest) Reset() {
	*x = GetMealsRequest{}
	mi := &file_hmly_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMealsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMealsRequest) ProtoMessage() {}

func (x *GetMealsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMealsRequest.ProtoReflect.Descriptor instead.
func (*GetMealsRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{16}
}

func (x *GetMealsRequest) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

type UpdateMealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	HouseholdId   string                 `protobuf:"bytes,4,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMealRequest) Reset() {
	*x = UpdateMealRequest{}
	mi := &file_hmly_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMealRequest) ProtoMessage() {}

func (x *UpdateMealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMealRequest.ProtoReflect.Descriptor instead.
func (*UpdateMealRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateMealRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMealRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMealRequest) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

type MealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	HouseholdId   string                 `protobuf:"bytes,3,opt,name=household_id,json=householdId,proto3" json:"household_id,omitempty"`
	ErrorMessage  *Error                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealResponse) Reset() {
	*x = MealResponse{}
	mi := &file_hmly_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealResponse) ProtoMessage() {}

func (x *MealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealResponse.ProtoReflect.Descriptor instead.
func (*MealResponse) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{18}
}

func (x *MealResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MealResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MealResponse) GetHouseholdId() string {
	if x != nil {
		return x.HouseholdId
	}
	return ""
}

func (x *MealResponse) GetErrorMessage() *Error {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

func (x *MealResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MealResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MealsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meals         []*MealResponse        `protobuf:"bytes,1,rep,name=meals,proto3" json:"meals,omitempty"`
	ErrorMessage  *Error                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealsResponse) Reset() {
	*x = MealsResponse{}
	mi := &file_hmly_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealsResponse) ProtoMessage() {}

func (x *MealsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealsResponse.ProtoReflect.Descriptor instead.
func (*MealsResponse) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{19}
}

func (x *MealsResponse) GetMeals() []*MealResponse {
	if x != nil {
		return x.Meals
	}
	return nil
}

func (x *MealsResponse) GetErrorMessage() *Error {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,3,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,6,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_hmly_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{20}
}

func (x *CreateEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEventRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CreateEventRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CreateEventRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateEventRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CreateEventRequest) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_hmly_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{21}
}

func (x *GetEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    *string                `protobuf:"bytes,1,opt,name=entityType,proto3,oneof" json:"entityType,omitempty"`
	Offset        *int32                 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	Limit         *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_hmly_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{22}
}

func (x *GetEventsRequest) GetEntityType() string {
	if x != nil && x.EntityType != nil {
		return *x.EntityType
	}
	return ""
}

func (x *GetEventsRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetEventsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,4,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,7,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_hmly_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEventRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *UpdateEventRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *UpdateEventRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *UpdateEventRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *UpdateEventRequest) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,4,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,7,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	ErrorMessage  *Error                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_hmly_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{24}
}

func (x *EventResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventResponse) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *EventResponse) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *EventResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *EventResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *EventResponse) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *EventResponse) GetErrorMessage() *Error {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

func (x *EventResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *EventResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type EventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventResponse       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	ErrorMessage  *Error                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsResponse) Reset() {
	*x = EventsResponse{}
	mi := &file_hmly_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse) ProtoMessage() {}

func (x *EventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse.ProtoReflect.Descriptor instead.
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{25}
}

func (x *EventsResponse) GetEvents() []*EventResponse {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventsResponse) GetErrorMessage() *Error {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_hmly_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{26}
}

func (x *VerifyTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ErrorMessage  *Error                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_hmly_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hmly_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_hmly_proto_rawDescGZIP(), []int{27}
}

func (x *VerifyTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyTokenResponse) GetErrorMessage() *Error {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

var File_hmly_proto protoreflect.FileDescriptor

const file_hmly_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"hmly.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\",\n" +
	"\x16CreateHouseholdRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"%\n" +
	"\x13GetHouseholdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x14GetHouseHoldsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"<\n" +
	"\x16UpdateHouseholdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x85\x01\n" +
	"\x17CreateHouseholdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x124\n" +
	"\rerror_message\x18\x03 \x01(\v2\n" +
	".api.ErrorH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\"\xbd\x01\n" +
	"\x11HouseholdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x124\n" +
	"\rerror_message\x18\x03 \x01(\v2\n" +
	".api.ErrorH\x00R\ferrorMessage\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAtB\x10\n" +
	"\x0e_error_message\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x94\x01\n" +
	"\x12HouseholdsResponse\x126\n" +
	"\n" +
	"households\x18\x01 \x03(\v2\x16.api.HouseholdResponseR\n" +
	"households\x124\n" +
	"\rerror_message\x18\x02 \x01(\v2\n" +
	".api.ErrorH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\"Q\n" +
	"\x13CreateMemberRequest\x12!\n" +
	"\fhousehold_id\x18\x01 \x01(\tR\vhouseholdId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\"\n" +
	"\x10GetMemberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x11GetMembersRequest\x12!\n" +
	"\fhousehold_id\x18\x01 \x01(\tR\vhouseholdId\"a\n" +
	"\x13UpdateMemberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fhousehold_id\x18\x02 \x01(\tR\vhouseholdId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\xe2\x01\n" +
	"\x0eMemberResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fhousehold_id\x18\x02 \x01(\tR\vhouseholdId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x124\n" +
	"\rerror_message\x18\x04 \x01(\v2\n" +
	".api.ErrorH\x00R\ferrorMessage\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAtB\x10\n" +
	"\x0e_error_message\"\x88\x01\n" +
	"\x0fMembersResponse\x12-\n" +
	"\amembers\x18\x01 \x03(\v2\x13.api.MemberResponseR\amembers\x124\n" +
	"\rerror_message\x18\x02 \x01(\v2\n" +
	".api.ErrorH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\"J\n" +
	"\x11CreateMealRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fhousehold_id\x18\x02 \x01(\tR\vhouseholdId\" \n" +
	"\x0eGetMealRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x0fGetMealsRequest\x12!\n" +
	"\fhousehold_id\x18\x01 \x01(\tR\vhouseholdId\"Z\n" +
	"\x11UpdateMealRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fhousehold_id\x18\x04 \x01(\tR\vhouseholdId\"\xdb\x01\n" +
	"\fMealResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fhousehold_id\x18\x03 \x01(\tR\vhouseholdId\x124\n" +
	"\rerror_message\x18\x04 \x01(\v2\n" +
	".api.ErrorH\x00R\ferrorMessage\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAtB\x10\n" +
	"\x0e_error_message\"\x80\x01\n" +
	"\rMealsResponse\x12'\n" +
	"\x05meals\x18\x01 \x03(\v2\x11.api.MealResponseR\x05meals\x124\n" +
	"\rerror_message\x18\x02 \x01(\v2\n" +
	".api.ErrorH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\"\xc1\x01\n" +
	"\x12CreateEventRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x03 \x01(\tR\n" +
	"entityType\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x1f\n" +
	"\vassigned_to\x18\x06 \x01(\tR\n" +
	"assignedTo\"!\n" +
	"\x0fGetEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x93\x01\n" +
	"\x10GetEventsRequest\x12#\n" +
	"\n" +
	"entityType\x18\x01 \x01(\tH\x00R\n" +
	"entityType\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x05H\x01R\x06offset\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x02R\x05limit\x88\x01\x01B\r\n" +
	"\v_entityTypeB\t\n" +
	"\a_offsetB\b\n" +
	"\x06_limit\"\xd1\x01\n" +
	"\x12UpdateEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x04 \x01(\tR\n" +
	"entityType\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12\x1f\n" +
	"\vassigned_to\x18\a \x01(\tR\n" +
	"assignedTo\"\xd2\x02\n" +
	"\rEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x04 \x01(\tR\n" +
	"entityType\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12\x1f\n" +
	"\vassigned_to\x18\a \x01(\tR\n" +
	"assignedTo\x124\n" +
	"\rerror_message\x18\b \x01(\v2\n" +
	".api.ErrorH\x00R\ferrorMessage\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAtB\x10\n" +
	"\x0e_error_message\"\x84\x01\n" +
	"\x0eEventsResponse\x12*\n" +
	"\x06events\x18\x01 \x03(\v2\x12.api.EventResponseR\x06events\x124\n" +
	"\rerror_message\x18\x02 \x01(\v2\n" +
	".api.ErrorH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\"*\n" +
	"\x12VerifyTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x8c\x01\n" +
	"\x13VerifyTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x124\n" +
	"\rerror_message\x18\x03 \x01(\v2\n" +
	".api.ErrorH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message2\xfb\x03\n" +
	"\x10HouseholdService\x12a\n" +
	"\x0fCreateHousehold\x12\x1b.api.CreateHouseholdRequest\x1a\x16.api.HouseholdResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/households\x12]\n" +
	"\fGetHousehold\x12\x18.api.GetHouseholdRequest\x1a\x16.api.HouseholdResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/households/{id}\x12[\n" +
	"\rGetHouseholds\x12\x19.api.GetHouseHoldsRequest\x1a\x17.api.HouseholdsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/households\x12f\n" +
	"\x0fUpdateHousehold\x12\x1b.api.UpdateHouseholdRequest\x1a\x16.api.HouseholdResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/v1/households/{id}\x12`\n" +
	"\x0fDeleteHousehold\x12\x18.api.GetHouseholdRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/households/{id}2\xd8\x03\n" +
	"\rMemberService\x12U\n" +
	"\fCreateMember\x12\x18.api.CreateMemberRequest\x1a\x13.api.MemberResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/members\x12Q\n" +
	"\tGetMember\x12\x15.api.GetMemberRequest\x1a\x13.api.MemberResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/members/{id}\x12h\n" +
	"\n" +
	"GetMembers\x12\x16.api.GetMembersRequest\x1a\x14.api.MembersResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/members/household/{household_id}\x12Z\n" +
	"\fUpdateMember\x12\x18.api.UpdateMemberRequest\x1a\x13.api.MemberResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/v1/members/{id}\x12W\n" +
	"\fDeleteMember\x12\x15.api.GetMemberRequest\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/members/{id}2\xb0\x03\n" +
	"\vMealService\x12M\n" +
	"\n" +
	"CreateMeal\x12\x16.api.CreateMealRequest\x1a\x11.api.MealResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/meals\x12I\n" +
	"\aGetMeal\x12\x13.api.GetMealRequest\x1a\x11.api.MealResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/meals/{id}\x12`\n" +
	"\bGetMeals\x12\x14.api.GetMealsRequest\x1a\x12.api.MealsResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/meals/household/{household_id}\x12R\n" +
	"\n" +
	"UpdateMeal\x12\x16.api.UpdateMealRequest\x1a\x11.api.MealResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/meals/{id}\x12Q\n" +
	"\n" +
	"DeleteMeal\x12\x13.api.GetMealRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/meals/{id}2\xab\x03\n" +
	"\fEventService\x12Q\n" +
	"\vCreateEvent\x12\x17.api.CreateEventRequest\x1a\x12.api.EventResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/events\x12M\n" +
	"\bGetEvent\x12\x14.api.GetEventRequest\x1a\x12.api.EventResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/events/{id}\x12K\n" +
	"\tGetEvents\x12\x15.api.GetEventsRequest\x1a\x13.api.EventsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/events\x12V\n" +
	"\vUpdateEvent\x12\x17.api.UpdateEventRequest\x1a\x12.api.EventResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/v1/events/{id}\x12T\n" +
	"\vDeleteEvent\x12\x14.api.GetEventRequest\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/v1/events/{id}B!Z\x1fgithub.com/hmlylab/common/protob\x06proto3"

var (
	file_hmly_proto_rawDescOnce sync.Once
	file_hmly_proto_rawDescData []byte
)

func file_hmly_proto_rawDescGZIP() []byte {
	file_hmly_proto_rawDescOnce.Do(func() {
		file_hmly_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hmly_proto_rawDesc), len(file_hmly_proto_rawDesc)))
	})
	return file_hmly_proto_rawDescData
}

var file_hmly_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_hmly_proto_goTypes = []any{
	(*CreateHouseholdRequest)(nil),  // 0: api.CreateHouseholdRequest
	(*GetHouseholdRequest)(nil),     // 1: api.GetHouseholdRequest
	(*GetHouseHoldsRequest)(nil),    // 2: api.GetHouseHoldsRequest
	(*UpdateHouseholdRequest)(nil),  // 3: api.UpdateHouseholdRequest
	(*CreateHouseholdResponse)(nil), // 4: api.CreateHouseholdResponse
	(*HouseholdResponse)(nil),       // 5: api.HouseholdResponse
	(*Error)(nil),                   // 6: api.Error
	(*HouseholdsResponse)(nil),      // 7: api.HouseholdsResponse
	(*CreateMemberRequest)(nil),     // 8: api.CreateMemberRequest
	(*GetMemberRequest)(nil),        // 9: api.GetMemberRequest
	(*GetMembersRequest)(nil),       // 10: api.GetMembersRequest
	(*UpdateMemberRequest)(nil),     // 11: api.UpdateMemberRequest
	(*MemberResponse)(nil),          // 12: api.MemberResponse
	(*MembersResponse)(nil),         // 13: api.MembersResponse
	(*CreateMealRequest)(nil),       // 14: api.CreateMealRequest
	(*GetMealRequest)(nil),          // 15: api.GetMealRequest
	(*GetMealsRequest)(nil),         // 16: api.GetMealsRequest
	(*UpdateMealRequest)(nil),       // 17: api.UpdateMealRequest
	(*MealResponse)(nil),            // 18: api.MealResponse
	(*MealsResponse)(nil),           // 19: api.MealsResponse
	(*CreateEventRequest)(nil),      // 20: api.CreateEventRequest
	(*GetEventRequest)(nil),         // 21: api.GetEventRequest
	(*GetEventsRequest)(nil),        // 22: api.GetEventsRequest
	(*UpdateEventRequest)(nil),      // 23: api.UpdateEventRequest
	(*EventResponse)(nil),           // 24: api.EventResponse
	(*EventsResponse)(nil),          // 25: api.EventsResponse
	(*VerifyTokenRequest)(nil),      // 26: api.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),     // 27: api.VerifyTokenResponse
	(*emptypb.Empty)(nil),           // 28: google.protobuf.Empty
}
var file_hmly_proto_depIdxs = []int32{
	6,  // 0: api.CreateHouseholdResponse.error_message:type_name -> api.Error
	6,  // 1: api.HouseholdResponse.error_message:type_name -> api.Error
	5,  // 2: api.HouseholdsResponse.households:type_name -> api.HouseholdResponse
	6,  // 3: api.HouseholdsResponse.error_message:type_name -> api.Error
	6,  // 4: api.MemberResponse.error_message:type_name -> api.Error
	12, // 5: api.MembersResponse.members:type_name -> api.MemberResponse
	6,  // 6: api.MembersResponse.error_message:type_name -> api.Error
	6,  // 7: api.MealResponse.error_message:type_name -> api.Error
	18, // 8: api.MealsResponse.meals:type_name -> api.MealResponse
	6,  // 9: api.MealsResponse.error_message:type_name -> api.Error
	6,  // 10: api.EventResponse.error_message:type_name -> api.Error
	24, // 11: api.EventsResponse.events:type_name -> api.EventResponse
	6,  // 12: api.EventsResponse.error_message:type_name -> api.Error
	6,  // 13: api.VerifyTokenResponse.error_message:type_name -> api.Error
	0,  // 14: api.HouseholdService.CreateHousehold:input_type -> api.CreateHouseholdRequest
	1,  // 15: api.HouseholdService.GetHousehold:input_type -> api.GetHouseholdRequest
	2,  // 16: api.HouseholdService.GetHouseholds:input_type -> api.GetHouseHoldsRequest
	3,  // 17: api.HouseholdService.UpdateHousehold:input_type -> api.UpdateHouseholdRequest
	1,  // 18: api.HouseholdService.DeleteHousehold:input_type -> api.GetHouseholdRequest
	8,  // 19: api.MemberService.CreateMember:input_type -> api.CreateMemberRequest
	9,  // 20: api.MemberService.GetMember:input_type -> api.GetMemberRequest
	10, // 21: api.MemberService.GetMembers:input_type -> api.GetMembersRequest
	11, // 22: api.MemberService.UpdateMember:input_type -> api.UpdateMemberRequest
	9,  // 23: api.MemberService.DeleteMember:input_type -> api.GetMemberRequest
	14, // 24: api.MealService.CreateMeal:input_type -> api.CreateMealRequest
	15, // 25: api.MealService.GetMeal:input_type -> api.GetMealRequest
	16, // 26: api.MealService.GetMeals:input_type -> api.GetMealsRequest
	17, // 27: api.MealService.UpdateMeal:input_type -> api.UpdateMealRequest
	15, // 28: api.MealService.DeleteMeal:input_type -> api.GetMealRequest
	20, // 29: api.EventService.CreateEvent:input_type -> api.CreateEventRequest
	21, // 30: api.EventService.GetEvent:input_type -> api.GetEventRequest
	22, // 31: api.EventService.GetEvents:input_type -> api.GetEventsRequest
	23, // 32: api.EventService.UpdateEvent:input_type -> api.UpdateEventRequest
	21, // 33: api.EventService.DeleteEvent:input_type -> api.GetEventRequest
	5,  // 34: api.HouseholdService.CreateHousehold:output_type -> api.HouseholdResponse
	5,  // 35: api.HouseholdService.GetHousehold:output_type -> api.HouseholdResponse
	7,  // 36: api.HouseholdService.GetHouseholds:output_type -> api.HouseholdsResponse
	5,  // 37: api.HouseholdService.UpdateHousehold:output_type -> api.HouseholdResponse
	28, // 38: api.HouseholdService.DeleteHousehold:output_type -> google.protobuf.Empty
	12, // 39: api.MemberService.CreateMember:output_type -> api.MemberResponse
	12, // 40: api.MemberService.GetMember:output_type -> api.MemberResponse
	13, // 41: api.MemberService.GetMembers:output_type -> api.MembersResponse
	12, // 42: api.MemberService.UpdateMember:output_type -> api.MemberResponse
	28, // 43: api.MemberService.DeleteMember:output_type -> google.protobuf.Empty
	18, // 44: api.MealService.CreateMeal:output_type -> api.MealResponse
	18, // 45: api.MealService.GetMeal:output_type -> api.MealResponse
	19, // 46: api.MealService.GetMeals:output_type -> api.MealsResponse
	18, // 47: api.MealService.UpdateMeal:output_type -> api.MealResponse
	28, // 48: api.MealService.DeleteMeal:output_type -> google.protobuf.Empty
	24, // 49: api.EventService.CreateEvent:output_type -> api.EventResponse
	24, // 50: api.EventService.GetEvent:output_type -> api.EventResponse
	25, // 51: api.EventService.GetEvents:output_type -> api.EventsResponse
	24, // 52: api.EventService.UpdateEvent:output_type -> api.EventResponse
	28, // 53: api.EventService.DeleteEvent:output_type -> google.protobuf.Empty
	34, // [34:54] is the sub-list for method output_type
	14, // [14:34] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_hmly_proto_init() }
func file_hmly_proto_init() {
	if File_hmly_proto != nil {
		return
	}
	file_hmly_proto_msgTypes[4].OneofWrappers = []any{}
	file_hmly_proto_msgTypes[5].OneofWrappers = []any{}
	file_hmly_proto_msgTypes[7].OneofWrappers = []any{}
	file_hmly_proto_msgTypes[12].OneofWrappers = []any{}
	file_hmly_proto_msgTypes[13].OneofWrappers = []any{}
	file_hmly_proto_msgTypes[18].OneofWrappers = []any{}
	file_hmly_proto_msgTypes[19].OneofWrappers = []any{}
	file_hmly_proto_msgTypes[22].OneofWrappers = []any{}
	file_hmly_proto_msgTypes[24].OneofWrappers = []any{}
	file_hmly_proto_msgTypes[25].OneofWrappers = []any{}
	file_hmly_proto_msgTypes[27].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hmly_proto_rawDesc), len(file_hmly_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_hmly_proto_goTypes,
		DependencyIndexes: file_hmly_proto_depIdxs,
		MessageInfos:      file_hmly_proto_msgTypes,
	}.Build()
	File_hmly_proto = out.File
	file_hmly_proto_goTypes = nil
	file_hmly_proto_depIdxs = nil
}
